# Generated by Django 4.2.1 on 2023-09-14 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=32, unique=True, verbose_name='Venue Name')),
                ('region', models.CharField(max_length=64, verbose_name='Region')),
                ('email', models.EmailField(max_length=64, verbose_name='Email')),
                ('phone', models.CharField(max_length=32, verbose_name='Phone Number')),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall', models.CharField(max_length=32, verbose_name='Hall')),
                ('area', models.IntegerField(default=0, verbose_name='Gross Area(sqm)')),
                ('h_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DataProcess.client')),
            ],
            options={
                'db_table': 'hall',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Statr Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('marking_days', models.IntegerField(default=0, verbose_name='Number of Marking Days')),
                ('status', models.CharField(default='NEW', max_length=64, verbose_name='Status')),
                ('j_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job', to='DataProcess.client')),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_halls', models.IntegerField(default=0, verbose_name='Number of Halls')),
                ('total_shows', models.IntegerField(default=0, verbose_name='Total Shows')),
                ('total_marks', models.IntegerField(default=0, verbose_name='Total Marks')),
                ('marks_day', models.IntegerField(default=0, verbose_name='Mark/Day')),
                ('marks_fte_day', models.IntegerField(default=0, verbose_name='Mark/FTE/Day')),
                ('marks_person_day', models.FloatField(default=0, verbose_name='Marks/Person/day')),
                ('marks_window', models.IntegerField(default=0, verbose_name='Avg # of marks/window')),
                ('marks_hall', models.IntegerField(default=0, verbose_name='Avg # of marks/hall')),
                ('halls_day', models.FloatField(default=0, verbose_name='Halls/Day')),
                ('fte', models.IntegerField(default=0, verbose_name='# FTE')),
                ('intern_helper', models.IntegerField(default=0, verbose_name='Intern/Helper')),
                ('fte_engineer_days', models.IntegerField(default=0, verbose_name='FTE/Engineer/Days')),
                ('intern_helper_days', models.IntegerField(default=0, verbose_name='Intern/Helper/Days')),
                ('fte_ratio', models.FloatField(default=0, verbose_name='FTE Ratio')),
                ('p_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='DataProcess.job')),
            ],
            options={
                'db_table': 'performance',
            },
        ),
        migrations.CreateModel(
            name='MarkingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.CharField(blank=True, max_length=32, null=True, verbose_name='Show')),
                ('colour', models.CharField(blank=True, max_length=16, null=True, verbose_name='Colour')),
                ('pre_corners', models.IntegerField(blank=True, null=True, verbose_name='Preliminary Corners')),
                ('pre_numbers', models.IntegerField(blank=True, null=True, verbose_name='Preliminary Numbers')),
                ('pre_others', models.IntegerField(blank=True, null=True, verbose_name='Preliminary Others')),
                ('pre_area', models.IntegerField(blank=True, null=True, verbose_name='Preliminary Area')),
                ('fin_corners', models.IntegerField(blank=True, null=True, verbose_name='Final Corners')),
                ('fin_numbers', models.IntegerField(blank=True, null=True, verbose_name='Final Numbers')),
                ('fin_others', models.IntegerField(blank=True, null=True, verbose_name='Final Others')),
                ('fin_area', models.IntegerField(blank=True, null=True, verbose_name='Final Area')),
                ('mj_hall', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mj', to='DataProcess.hall')),
                ('mj_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mj', to='DataProcess.job')),
            ],
            options={
                'db_table': 'markingJob',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('type', models.CharField(max_length=32, verbose_name='Type')),
                ('days', models.IntegerField(verbose_name='Working days on-site')),
                ('hall', models.CharField(max_length=32, verbose_name='Hall')),
                ('e_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='DataProcess.job')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
