# Generated by Django 4.2.1 on 2023-09-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataProcess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='type',
            field=models.CharField(choices=[('Full-time-employee', 'Full-time-employee'), ('Helper', 'Helper')], default='Full-time-employee', max_length=32, verbose_name='Type'),
        ),
    ]
