# Generated by Django 4.2.1 on 2023-10-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataProcess', '0003_alter_markingjob_mj_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='marks_day',
            field=models.FloatField(default=0, verbose_name='Mark/Day'),
        ),
    ]
