# Generated by Django 4.2.1 on 2023-10-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataProcess', '0004_alter_performance_marks_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markingjob',
            name='show',
        ),
        migrations.AddField(
            model_name='job',
            name='show',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Show'),
        ),
        migrations.AddField(
            model_name='job',
            name='total_marks_day',
            field=models.FloatField(default=0, verbose_name='Total Mark/Day'),
        ),
    ]
