# Generated by Django 4.2.1 on 2025-02-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=32, null=True, verbose_name='user_email'),
        ),
    ]
