name: Backend-dev-CICD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Django-backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: Django-backend  
          tags: django-app:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Run docker compose
        run: |
          sh build-project-docker.sh

      - name: Run the pytest
        run: |
          docker-compose exec -T backend pytest

      - name: Shot down docker-compose
        run: |
          docker-compose down
